import { NewCard } from "./schema.ts";

export const cardsSeedData: NewCard[] = [
  {
    name: "Lunar Lepus",
    rarity: "SSR",
    attack: 5,
    defense: 1,
    description: "If your movie is Thriller OR it's facing a Thriller, gain +4 ATK",
  },
  {
    name: "Sprint Hare",
    rarity: "SSR",
    attack: 7,
    defense: -2,
    description: "Your movie always strikes first. If facing Sci-Fi, double all damage",
  },
  {
    name: "Angora Assassin",
    rarity: "SSR",
    attack: 6,
    defense: 2,
    description: "If facing Noir or Crime, 30% chance to instantly win this matchup",
  },
  {
    name: "Velveteen Vanguard",
    rarity: "SSR",
    attack: 4,
    defense: 4,
    description: "If your movie is Animation, ignore opponent's DEF bonuses",
  },
  {
    name: "Warren Warrior",
    rarity: "SSR",
    attack: 4,
    defense: 2,
    description: "If your movie is Action, deal 2x damage this round",
  },
  {
    name: "Fluffball Guardian",
    rarity: "SSR",
    attack: 0,
    defense: 7,
    description: "If facing Fantasy, your movie takes half damage this round",
  },
  {
    name: "Magician's Rabbit",
    rarity: "SSR",
    attack: 4,
    defense: 3,
    description: "If either movie is Fantasy, swap your ATK and DEF bonuses",
  },
  {
    name: "Thumper's Revenge",
    rarity: "SSR",
    attack: 6,
    defense: 0,
    description: "If facing a Horror movie, deal triple damage but your movie takes 2 self-damage",
  },
  {
    name: "Celestial Cottontail",
    rarity: "SSR",
    attack: 5,
    defense: 5,
    description: "During full moon rounds, all your stats are doubled",
  },
  {
    name: "Emperor Bunny",
    rarity: "SSR",
    attack: 6,
    defense: 4,
    description: "If your movie is Historical, command other cards to grant +2/+2 to all allies",
  },

  {
    name: "Cottontail Critic",
    rarity: "SR",
    attack: 3,
    defense: 1,
    description: "If your movie is a Comedy, deal +5 bonus damage",
  },
  {
    name: "Burrow Bunny",
    rarity: "SR",
    attack: 1,
    defense: 6,
    description: "If your movie is Drama, reduce incoming damage by 4",
  },
  {
    name: "Carrot Crusader",
    rarity: "SR",
    attack: 3,
    defense: 2,
    description: "After your movie wins, heal it for 3 HP",
  },
  {
    name: "Hopscotch Hare",
    rarity: "SR",
    attack: 2,
    defense: 3,
    description: "If your movie is Romance, attack the same opponent twice for half damage each",
  },
  {
    name: "Ears of Wisdom",
    rarity: "SR",
    attack: 2,
    defense: 5,
    description: "If your movie is Mystery, peek at opponent's card and gain +3 DEF",
  },
  {
    name: "Snowshoe Sentinel",
    rarity: "SR",
    attack: 3,
    defense: 5,
    description: "Reflect 3 damage back to attacker when your movie is hit",
  },
  {
    name: "Jackalope Jester",
    rarity: "SR",
    attack: 5,
    defense: 2,
    description: "If your movie is Western, flip a coin: Heads = double ATK, Tails = double DEF",
  },
  {
    name: "Lop-Eared Librarian",
    rarity: "SR",
    attack: 1,
    defense: 4,
    description: "If your movie is Historical or Documentary, draw 1 extra card next round",
  },
  {
    name: "Rex Rabbit Rogue",
    rarity: "SR",
    attack: 4,
    defense: 3,
    description: "If your movie is Period Drama, steal 3 HP from the opposing movie",
  },
  {
    name: "Holland Lop Healer",
    rarity: "SR",
    attack: 1,
    defense: 5,
    description: "If your movie is Romance, heal all your movies for 2 HP at round end",
  },
  {
    name: "Binkying Bunny",
    rarity: "SR",
    attack: 2,
    defense: 2,
    description: "Gains +1/+1 permanently for each Comedy you've won this match",
  },
  {
    name: "Dust Bunny Drifter",
    rarity: "SR",
    attack: 3,
    defense: 1,
    description: "First attack against your movie each match deals 0 damage",
  },
  {
    name: "Thunder Thumper",
    rarity: "SR",
    attack: 5,
    defense: 3,
    description: "If your movie is Action, stun opponent's card for 1 turn",
  },
  {
    name: "Mystic Moon Rabbit",
    rarity: "SR",
    attack: 3,
    defense: 4,
    description: "If your movie is Fantasy or Anime, shuffle and redraw opponent's hand",
  },
  {
    name: "Noir Netherlander",
    rarity: "SR",
    attack: 4,
    defense: 2,
    description: "If your movie is Mystery or Thriller, gain stealth - can't be targeted",
  },

  {
    name: "Meadow Hopper",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Balanced bunny with steady performance in any genre",
  },
  {
    name: "Fluffy Defender",
    rarity: "R",
    attack: 1,
    defense: 3,
    description: "Protects your movie with extra fluff",
  },
  {
    name: "Swift Striker",
    rarity: "R",
    attack: 3,
    defense: 1,
    description: "Quick attacks deal bonus damage to slower opponents",
  },
  {
    name: "Garden Guardian",
    rarity: "R",
    attack: 2,
    defense: 3,
    description: "If defending, gain +1 DEF",
  },
  {
    name: "Clover Companion",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Lucky bunny - 15% chance to dodge attacks",
  },
  {
    name: "Timid Cottontail",
    rarity: "R",
    attack: 1,
    defense: 4,
    description: "Hides effectively but deals minimal damage",
  },
  {
    name: "Brave Bunkin",
    rarity: "R",
    attack: 3,
    defense: 2,
    description: "Courageously faces any opponent",
  },
  {
    name: "Carrot Muncher",
    rarity: "R",
    attack: 2,
    defense: 1,
    description: "After battle, gain 1 carrot currency",
  },
  {
    name: "Twitchy Nose",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Senses danger - reveals opponent's next move",
  },
  {
    name: "Flopsy Fighter",
    rarity: "R",
    attack: 3,
    defense: 1,
    description: "Floppy ears distract enemies for +1 ATK",
  },
  {
    name: "Whisker Warrior",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Whiskers detect weakness for accurate strikes",
  },
  {
    name: "Bouncing Betty",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Bounces around making her harder to hit",
  },
  {
    name: "Nibbles the Brave",
    rarity: "R",
    attack: 3,
    defense: 2,
    description: "Small but mighty, never backs down",
  },
  {
    name: "Powder Puff",
    rarity: "R",
    attack: 1,
    defense: 3,
    description: "Soft and cuddly, absorbs damage well",
  },
  {
    name: "Hopster",
    rarity: "R",
    attack: 2,
    defense: 1,
    description: "Hops into action with enthusiasm",
  },
  {
    name: "Velvet Ears",
    rarity: "R",
    attack: 1,
    defense: 2,
    description: "Soft ears cushion blows",
  },
  {
    name: "Dash Rabbit",
    rarity: "R",
    attack: 3,
    defense: 0,
    description: "All speed, no defense",
  },
  {
    name: "Gentle Giant",
    rarity: "R",
    attack: 1,
    defense: 4,
    description: "Large bunny with a kind heart",
  },
  {
    name: "Cotton Scout",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Scouts ahead to warn of danger",
  },
  {
    name: "Burrow Builder",
    rarity: "R",
    attack: 1,
    defense: 3,
    description: "Creates defensive positions",
  },
  {
    name: "Field Runner",
    rarity: "R",
    attack: 3,
    defense: 1,
    description: "Runs circles around enemies",
  },
  {
    name: "Lettuce Lover",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Well-fed and ready to rumble",
  },
  {
    name: "Warren Watcher",
    rarity: "R",
    attack: 2,
    defense: 3,
    description: "Keeps watch over the warren",
  },
  {
    name: "Midnight Hopper",
    rarity: "R",
    attack: 2,
    defense: 2,
    description: "Active at night with enhanced senses",
  },
  {
    name: "Spring Bunny",
    rarity: "R",
    attack: 2,
    defense: 1,
    description: "Springs into action when needed",
  },
];
